# Automatically label PRs based on changed files

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '*.md'
      - 'docs/**/*'

components:
  - changed-files:
    - any-glob-to-any-file: 'src/components/**/*'

ui:
  - changed-files:
    - any-glob-to-any-file: 'src/components/ui/**/*'

sections:
  - changed-files:
    - any-glob-to-any-file: 'src/components/sections/**/*'

animations:
  - changed-files:
    - any-glob-to-any-file: 'src/components/animations/**/*'

blog:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/app/blog/**/*'
      - 'src/lib/blog/**/*'

styling:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.css'
      - 'tailwind.config.ts'
      - 'postcss.config.mjs'

types:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/types/**/*'
      - '**/*.d.ts'

data:
  - changed-files:
    - any-glob-to-any-file: 'src/data/**/*'

config:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/config/**/*'
      - '*.config.*'
      - '.env.example'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'

ci-cd:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'

i18n:
  - changed-files:
    - any-glob-to-any-file: 'src/lib/i18n/**/*'
